
# Build Stage
FROM node:22-alpine3.20 AS build_stage

WORKDIR /app

COPY ./ ./

RUN npm i
RUN npm run pre-commit
RUN npm run build:ncc

# Run Stage
FROM node:22-alpine3.20 AS run_stage

WORKDIR /app

COPY --from=build_stage ./app/dist ./dist
COPY --from=build_stage ./app/.env.dev ./.env

EXPOSE 3600

CMD [ "node", "./dist/index.js" ]


